---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-cake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-cake
  template:
    metadata:
      labels:
        app: wordpress-cake
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service
            - name: WORDPRESS_DB_USER
              value: wpuser-cake
            - name: WORDPRESS_DB_PASSWORD
              value: wppass-cake
            - name: WORDPRESS_DB_NAME
              value: wpdb_cake
          image: wordpress:6.8.3
          name: wordpress-cake
          ports: [{ containerPort: 80 }]
          volumeMounts:
            - mountPath: /var/www/html/wp-content/uploads
              name: wp-content
          nodeSelector:
            kubernetes.io/hostname: k8s-worker1
          volumes:
            - name: wp-content
              persistentVolumeClaim:
                claimName: wp-pvc